### ISSUE TITLE
Bunch of errors when closing window

### ISSUE THREAD

**Issue by edemen** [edemen/camera-qr-wifi#5]
When the frame is closed, many errors are quickly dumped to console before Exit

**Comment by edemen** [comment]
~~~~
Error: null
java.lang.NullPointerException
	at com.google.zxing.client.j2se.BufferedImageLuminanceSource.<init>(BufferedImageLuminanceSource.java:42)
	at tech.utilis.cameraqrwifi.QRParser.parseWifi(QRParser.java:41)
	at tech.utilis.cameraqrwifi.Main.lambda$main$1(Main.java:44)
	at java.lang.Thread.run(Thread.java:748)
Retry
~~~~

**Comment by edemen** [comment]
Also, when WiFi decoded but not connected, must exist program
